// Generated by IB v0.7.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <CoreGraphics/CoreGraphics.h>
#import <CoreLocation/CoreLocation.h>
#import <Foundation/Foundation.h>
#import <MapKit/MapKit.h>
#import <MobileCoreServices/MobileCoreServices.h>
#import <QuartzCore/QuartzCore.h>
#import <Security/Security.h>
#import <SystemConfiguration/SystemConfiguration.h>
#import <UIKit/UIKit.h>

@interface MenuDrawer: UIViewController
-(IBAction) setup;

@end

@interface AppDelegate: UIViewController
-(IBAction) show_menu;

@end

@interface AboutLayout: MK::Layout
-(IBAction) layout;
-(IBAction) base_settings;
-(IBAction) add_constraints;

@end

@interface ShowLayout: MK::Layout
-(IBAction) layout;
-(IBAction) add_constraints;

@end

@interface Alert: NSObject
-(IBAction) after_save:(id) sender;
-(IBAction) after_delete:(id) sender;
-(IBAction) cancel_alert;
-(IBAction) update_alert;
-(IBAction) settings;
-(IBAction) has_or_gets_permission;
-(IBAction) alert_date;
-(IBAction) morning_alert_date;
-(IBAction) beforehand_alert_date;
-(IBAction) starting_alert_date;
-(IBAction) alert_title;
-(IBAction) notification_id;

@end

@interface AlertSettings: NSObject
-(IBAction) initialize;
-(IBAction) update_settings:(id) settings_hash;

@end

@interface Event: NSObject
-(IBAction) handle_results:(id) loaded_events;
-(IBAction) event_attrs_hash:(id) result;
-(IBAction) finish_event_load:(id) result;
-(IBAction) clear_removed_events:(id) loaded_events;
-(IBAction) factory:(id) attrs;

@end

@interface MapAnnotation: NSObject
@end

@interface AboutScreen: UIViewController
-(IBAction) on_load;
-(IBAction) setup_links;

@end

@interface Edit: UIViewController
-(IBAction) on_load;
-(IBAction) table_data;
-(IBAction) observe_form;
-(IBAction) update_alerts:(id) settings;

@end

@interface Index: UIViewController
-(IBAction) on_load;
-(IBAction) table_data;
-(IBAction) alert_choosen:(id) args;
-(IBAction) events;

@end

@interface Show: UIViewController
-(IBAction) on_load;
-(IBAction) start_end_time;
-(IBAction) setup_alerts;
-(IBAction) set_alert_text;
-(IBAction) setup_map;
-(IBAction) setup_notifications;
-(IBAction) dataDidChange:(id) notification;

@end

@interface MainScreen: UIViewController
-(IBAction) on_load;

@end

@interface NavigationScreen: UIViewController
-(IBAction) table_data;
-(IBAction) swap_center_controller:(id) screen_class;

@end

@interface SettingsScreen: UIViewController
-(IBAction) on_load;
-(IBAction) table_data;

@end

@interface ApplicationStylesheet: RubyMotionQuery::Stylesheet
-(IBAction) application_setup;
-(IBAction) root_view:(id) st;
-(IBAction) root_scroll_view:(id) st;
-(IBAction) line:(id) st;
-(IBAction) navigation_icon:(id) st;
-(IBAction) standard_button:(id) st;
-(IBAction) standard_label:(id) st;
-(IBAction) right_chevron:(id) st;

@end

@interface SettingsStylesheet: ApplicationStylesheet
@end

@interface UIViewStyler: NSObject
@end

@interface EditStylesheet: ApplicationStylesheet
@end

@interface IndexStylesheet: ApplicationStylesheet
-(IBAction) event_date:(id) st;
-(IBAction) event_title:(id) st;
-(IBAction) event_time:(id) st;

@end

@interface ShowStylesheet: ApplicationStylesheet
-(IBAction) setup;
-(IBAction) root_view:(id) st;
-(IBAction) title_container:(id) st;
-(IBAction) map_container:(id) st;
-(IBAction) alerts_container:(id) st;
-(IBAction) series_container:(id) st;
-(IBAction) event_description:(id) st;
-(IBAction) venue_description:(id) st;
-(IBAction) event_title:(id) st;
-(IBAction) detail_cell:(id) st;
-(IBAction) event_date:(id) st;
-(IBAction) event_time:(id) st;
-(IBAction) event_location:(id) st;
-(IBAction) venue_map:(id) st;
-(IBAction) venue_address:(id) st;
-(IBAction) label:(id) st;
-(IBAction) long_label:(id) st;
-(IBAction) setting:(id) st;
-(IBAction) label_base:(id) st;
-(IBAction) description_paragraph:(id) st;

@end

@interface MainStylesheet: ApplicationStylesheet
-(IBAction) setup;
-(IBAction) hello_world:(id) st;

@end

@interface NavigationControllerStylesheet: ApplicationStylesheet
-(IBAction) setup;
-(IBAction) table:(id) st;
-(IBAction) navigation_cell_height;
-(IBAction) navigation_cell:(id) st;
-(IBAction) cell_label:(id) st;

@end

@interface EventCell: UIViewController
-(IBAction) start_time;
-(IBAction) title;
-(IBAction) humanized_time:(id) time;
-(IBAction) humanized_date:(id) time;

@end

